version: '3'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
      args:
        - IMAGE=gcr.io/voltaic-mode-410817/simple-paypal-api:latest
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    container_name: simple-paypal-api
    ports:
      - "8080:8080"
    env_file:
      - ./.env