version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    ports:
      - "${PORT}:${PORT}"
    env_file:
      - ./.env
    depends_on:
      - redis
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - REDIS_PASSWORD=123
  redis:
    image: "redis:7.2.4-alpine"
    restart: always
    command: redis-server --save 20 1 --loglevel warning --requirepass 123
    ports:
      - 6379:6379
